bind dropbox app token, secret, etc.

diff --git a/Gyazo/uploader b/Gyazo/uploader
--- a/Gyazo/uploader
+++ b/Gyazo/uploader
@@ -20,7 +20,7 @@
 #
 
 #Default configuration file
-CONFIG_FILE=~/.dropbox_uploader
+CONFIG_FILE=~/Library/Gyazo/dropbox
 
 #Default chunk size in Mb for the upload process
 #It is recommended to increase this value only if you have enough free space on your /tmp partition
@@ -870,30 +870,33 @@ if [ -f "$CONFIG_FILE" ]; then
 #NEW SETUP...
 else
 
-    echo -ne "\n This is the first time you run this script.\n"
-    echo -ne " Please open this URL from your Browser, and access using your account:\n\n -> $APP_CREATE_URL\n"
-    echo -ne "\n If you haven't already done, click \"Create an App\" and fill in the\n"
-    echo -ne " form with the following data:\n\n"
-    echo -ne "  App name: MyUploader$RANDOM$RANDOM\n"
-    echo -ne "  App type: Core\n"
-    echo -ne "  Permission type: App folder or Full Dropbox\n\n"
-    echo -ne " Now, click on the \"Create\" button.\n\n"
+    #echo -ne "\n This is the first time you run this script.\n"
+    #echo -ne " Please open this URL from your Browser, and access using your account:\n\n -> $APP_CREATE_URL\n"
+    #echo -ne "\n If you haven't already done, click \"Create an App\" and fill in the\n"
+    #echo -ne " form with the following data:\n\n"
+    #echo -ne "  App name: MyUploader$RANDOM$RANDOM\n"
+    #echo -ne "  App type: Core\n"
+    #echo -ne "  Permission type: App folder or Full Dropbox\n\n"
+    #echo -ne " Now, click on the \"Create\" button.\n\n"
 
-    echo -ne " When your new App is successfully created, please type the\n"
-    echo -ne " App Key, App Secret and the Access level:\n\n"
+    #echo -ne " When your new App is successfully created, please type the\n"
+    #echo -ne " App Key, App Secret and the Access level:\n\n"
 
     #Getting the app key and secret from the user
-    while (true); do
+    #while (true); do
 
-        echo -n " # App key: "
-        read APPKEY
+        #echo -n " # App key: "
+        #read APPKEY
 
-        echo -n " # App secret: "
-        read APPSECRET
+        #echo -n " # App secret: "
+        #read APPSECRET
 
-        echo -n " # Access level you have chosen, App folder or Full Dropbox [a/f]: "
-        read ACCESS_LEVEL
+        #echo -n " # Access level you have chosen, App folder or Full Dropbox [a/f]: "
+        #read ACCESS_LEVEL
 
+        APPKEY="yz07e982uv9v94m"
+        APPSECRET="48jzq12c944qvg3"
+        ACCESS_LEVEL="a"
         if [ "$ACCESS_LEVEL" == "a" ]; then
             ACCESS_LEVEL="sandbox"
             ACCESS_MSG="App Folder"
@@ -902,37 +905,44 @@ else
             ACCESS_MSG="Full Dropbox"
         fi
 
-        echo -ne "\n > App key is $APPKEY, App secret is $APPSECRET and Access level is $ACCESS_MSG, it's ok? [y/n]"
-        read answer
-        if [ "$answer" == "y" ]; then
-            break;
-        fi
+        #echo -ne "\n > App key is $APPKEY, App secret is $APPSECRET and Access level is $ACCESS_MSG, it's ok? [y/n]"
+        #read answer
+        #if [ "$answer" == "y" ]; then
+        #    break;
+        #fi
 
-    done
+    #done
 
     #TOKEN REQUESTS
-    echo -ne "\n > Token request... "
-    time=$(utime)
-    $CURL_BIN $CURL_ACCEPT_CERTIFICATES -s --show-error --globoff -i -o $RESPONSE_FILE --data "oauth_consumer_key=$APPKEY&oauth_signature_method=PLAINTEXT&oauth_signature=$APPSECRET%26&oauth_timestamp=$time&oauth_nonce=$RANDOM" "$API_REQUEST_TOKEN_URL" 2> /dev/null
-    check_curl_status
-    OAUTH_TOKEN_SECRET=$(sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' "$RESPONSE_FILE")
-    OAUTH_TOKEN=$(sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' "$RESPONSE_FILE")
+    #echo -ne "\n > Token request... "
+    RESPONSE_FILE="$TMP_DIR/.gayzobox_oauth.$(whoami)"
+    if [ ! -f $RESPONSE_FILE ]; then
+        time=$(utime)
+        $CURL_BIN $CURL_ACCEPT_CERTIFICATES -s --show-error --globoff -i -o $RESPONSE_FILE --data "oauth_consumer_key=$APPKEY&oauth_signature_method=PLAINTEXT&oauth_signature=$APPSECRET%26&oauth_timestamp=$time&oauth_nonce=$RANDOM" "$API_REQUEST_TOKEN_URL" 2> /dev/null
+        check_curl_status
+        OAUTH_TOKEN_SECRET=$(sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' "$RESPONSE_FILE")
+        OAUTH_TOKEN=$(sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' "$RESPONSE_FILE")
 
-    if [ -n "$OAUTH_TOKEN" -a -n "$OAUTH_TOKEN_SECRET" ]; then
-        echo -ne "OK\n"
-    else
-        echo -ne " FAILED\n\n Please, check your App key and secret...\n\n"
-        remove_temp_files
+        open "${API_USER_AUTH_URL}?oauth_token=$OAUTH_TOKEN"
         exit 1
-    fi
+    else
+        OAUTH_TOKEN_SECRET=$(sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' "$RESPONSE_FILE")
+        OAUTH_TOKEN=$(sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' "$RESPONSE_FILE")
 
-    while (true); do
+    #if [ -n "$OAUTH_TOKEN" -a -n "$OAUTH_TOKEN_SECRET" ]; then
+    #    echo -ne "OK\n"
+    #else
+    #    echo -ne " FAILED\n\n Please, check your App key and secret...\n\n"
+    #    remove_temp_files
+    #    exit 1
+    #fi
 
         #USER AUTH
-        echo -ne "\n Please visit this URL from your Browser, and allow Dropbox Uploader\n"
-        echo -ne " to access your DropBox account:\n\n --> ${API_USER_AUTH_URL}?oauth_token=$OAUTH_TOKEN\n"
-        echo -ne "\nPress enter when done...\n"
-        read
+        #echo -ne "\n Please visit this URL from your Browser, and allow Dropbox Uploader\n"
+        #echo -ne " to access your DropBox account:\n\n --> ${API_USER_AUTH_URL}?oauth_token=$OAUTH_TOKEN\n"
+        #open "${API_USER_AUTH_URL}?oauth_token=$OAUTH_TOKEN"
+        #echo -ne "\nPress enter when done...\n"
+        #read
 
         #API_ACCESS_TOKEN_URL
         echo -ne " > Access Token request... "
@@ -954,12 +964,13 @@ else
             echo "OAUTH_ACCESS_TOKEN_SECRET=$OAUTH_ACCESS_TOKEN_SECRET" >> "$CONFIG_FILE"
 
             echo -ne "\n Setup completed!\n"
-            break
         else
+            remove_temp_files
+            exit 1
             print " FAILED\n"
         fi
 
-    done;
+    fi
 
     remove_temp_files
     exit 0
